apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-zyrv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iacf-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-zyrv@sha256:4910000a53cfda3b784ddfa54d37abd3b0e04a716d62caa8db9df341231296c9
        name: my-python
        resources: {}
status: {}
